version: "3.9"
services:
  qprod_ser_qin_sunset:
    tty: true
    stdin_open: true
    container_name: qprod_con_qin_sunset
    image: pointeldevs/run_java
    volumes:
      - ${QIN_ROOT}/Prod:/root/Prod
    environment:
      - QIN_ROOT=/root
    ports:
      - 5488:5488
    expose:
      - 5488
    networks:
      - qin_net_run
    restart: always
    working_dir: /root/Prod
    command: ./start.sh

networks:
  qin_net_run:
    external: true